---
- name: start postgresdb container
  docker:
    name: postgres
    image: postgres
    hostname: postgres-server
    state: started
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar

- name: start sonarqube container
  docker:
    name: sonarqube
    image: sonarqube:5.2
    hostname: sonarqube-server
    state: started
    links:
      - "postgres:postgres"
    ports:
      - "9000:9000"
    env:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
