---
- name: start eureka-server
  docker:
    name: eureka-server
    hostname: eureka
    image: registry.aliyuncs.com/leansw/discovery-service
    state: started
    insecure_registry: yes
    ports:
      - "8761:8761"
