---
- name: start eureka-server
  docker:
    name: eureka-server
    image: registry:5000/leansw/discovery-service
    state: started
    insecure_registry: yes
    ports:
      - "8761:8761"
  tags:
    - docker
    - identity
    - cd-metrics
