---
- name: start eureka-server
  docker:
    name: eureka-server
    hostname: eureka-server
    image: registry:5000/leansw/discovery-service
    state: reloaded
    insecure_registry: yes
    memory_limit: 216MB
    ports:
      - "8761:8761"
  tags:
    - docker
    - identity
    - cd-metrics
    - code-metrics
    - deliflow-webapp
