---
- hosts: all
  remote_user: root
  roles:
     - docker
     - mongodb
     - mysql
     - sonarqube
     - gocd-server
     - gocd-agent
     - eureka-server
     - identity-server
     - auth-server
     - cd-metrics
     - code-metrics
     - deliflow-webapp
