---
- hosts: all
  remote_user: twer
  vars:
    production_mode: true
  roles:
     - docker
     - mongodb
     - eureka-server
     - identity-server
     - auth-server
     - sonarqube
     - cd-metrics
     - code-metrics
     - deliflow-webapp
