---
- script: yum-repo-docker.sh
  tags:
    - docker
- yum: name=docker-engine state=latest
  tags:
    - docker
- service: name=docker state=restarted
  tags:
    - docker
- easy_install: name=pip
  tags:
    - docker
- pip: name=docker-py version=1.1.0
  tags:
    - docker
