---
- name: start auth-server container
  docker:
    name: auth-server
    hostname: auth
    image: registry:5000/leansw/auth-server:release
    state: started
    memory_limit: 216MB
    ports:
      - "8081:8080"
    links:
      - "eureka-server:eureka-server"
    insecure_registry: yes
    env:
      ACTIVE_PROFILE: default
