---
- name: start auth-server container
  docker:
    name: auth-server
    image: registry:5000/leansw/auth-server:release
    state: reloaded
    pull: always
    ports:
      - "8081:8080"
    links:
      - "eureka-server:eureka-server"
    insecure_registry: yes
    env:
      ACTIVE_PROFILE: default
  tags:
    - docker
    - auth-server
