---
- name: create config volume mapping gocd config file
  file: path=/data/var/go state=directory mode=0755

- name: create config volume mapping gocd config file
  file: path=/data/etc/go state=directory mode=0777

- name: create config volume mapping gocd plugins
  file: path=/data/var/lib/go-server/plugins/external state=directory mode=777

- name: upload gocd password.properties
  copy: src=password.properties dest=/data/var/go/password.properties mode=777

- name: upload gocd cruise-config.xml
  copy: src=cruise-config.xml dest=/data/etc/go/cruise-config.xml mode=777
# get_url in aliyun will be time out
# - name: wget deliflow notofy plugins
#   get_url: timeout=20 url=https://github.com/tw-leansw/leansw-plugins-status-notifier/releases/download/latested/lean-status-notifier-1.0-SNAPSHOT.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777

# - name: wget deliflow oauth plugins
#   get_url: timeout=20 url=https://github.com/tw-leansw/leansw-plugins-oauth-login/releases/download/1.0/deliflow-oauth-login-1.0.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777
#
# - name: wget gocd artifactory plugins
#   get_url: timeout=20 url=https://github.com/tusharm/go-artifactory-plugin/releases/download/v1.0.0-62/go-artifactory-plugin-1.0.0-62.distribution.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777
#
# - name: wget gocd github pull request poller plugins
#   get_url: timeout=20 url=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.2.4/github-pr-poller-1.2.4.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777
#
# - name: wget gocd github pull request status plugins
#   get_url: timeout=20 url=https://github.com/gocd-contrib/gocd-build-status-notifier/releases/download/1.1/github-pr-status-1.1.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777

- name: copy deliflow notify plugins
  copy: src=lean-status-notifier-1.0-SNAPSHOT.jar dest=/data/var/lib/go-server/plugins/external/

- name: copy deliflow oauth plugins
  copy: src=deliflow-oauth-login-1.0.jar dest=/data/var/lib/go-server/plugins/external/

- name: copy github pull request poller plugins
  copy: src=github-pr-poller-1.2.4.jar dest=/data/var/lib/go-server/plugins/external/

- name: copy github pull request status plugins
  copy: src=github-pr-status-1.1.jar dest=/data/var/lib/go-server/plugins/external/

- name: copy artifactory plugins
  copy: src=go-artifactory-plugin-1.0.0-62.distribution.jar dest=/data/var/lib/go-server/plugins/external/

- name: start gocd-server container
  docker:
    name: gocd-server
    hostname: gocd
    image: gocd/gocd-server
    state: reloaded
    insecure_registry: yes
    ports:
      - "8153:8153"
    volumes:
      - /data/var/go:/var/go:rw
      - /data/etc/go:/etc/go:rw
      - /data/var/lib/go-server/plugins:/var/lib/go-server/plugins:rw
  register: gocd_server_container

- debug: var=gocd_server_container
  when: gocd_server_container
