---
- name: create config volume mapping gocd config file
  file: path=/data/var/go state=directory mode=0755

- name: create config volume mapping gocd config file
  file: path=/data/etc/go state=directory mode=0777

- name: create config volume mapping gocd plugins
  file: path=/data/var/lib/go-server/plugins/external state=directory mode=0777

- name: upload gocd password.properties
  copy: src=password.properties dest=/data/var/go/password.properties mode=777

- name: upload gocd cruise-config.xml
  copy: src=cruise-config.xml dest=/data/etc/go/cruise-config.xml mode=777

- name: wget deliflow notofy plugins
  get_url: url=https://github.com/tw-leansw/leansw-plugins-status-notifier/releases/download/latested/lean-status-notifier-1.0-SNAPSHOT.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777

- name: wget deliflow oauth plugins
  get_url: url=https://github.com/tw-leansw/leansw-plugins-oauth-login/releases/download/1.0/deliflow-oauth-login-1.0.jar dest=/data/var/lib/go-server/plugins/external/ mode=0777

- name: start gocd-server container
  docker:
    name: gocd-server
    hostname: gocd
    image: gocd/gocd-server
    state: reloaded
    insecure_registry: yes
    ports:
      - "8153:8153"
    volumes:
      - /data/var/go:/var/go
      - /data/etc/go:/etc/go
      - /data/var/lib/go-server/plugins/external:/var/lib/go-server/plugins/external
  register: gocd_server_container

- debug: var=gocd_server_container
  when: gocd_server_container
