---
- name: start identity-server container
  docker:
    name: identity-server
    image: "{{ identity_docker_images }}"
    state: reloaded
    pull: always
    memory_limit: 512MB
    insecure_registry: yes
    links:
      - "mysql:mysql-server"
      - "eureka-server:eureka-server"
      - "gocd-server:gocd-server"
    env:
      ACTIVE_PROFILE: "{{ active_profile }}"
  tags:
    - docker
    - identity
