---
- name: start mysql database instance for identity
  docker:
    name: mysql
    image: mysql:5.5
    state: started
    hostname: mysql-server
    memory_limit: 1024MB
    ports:
      - "3306:3306"
    volumes:
      - /data/deliflow/mysql:/var/lib/mysql
    env:
      MYSQL_DATABASE: deliflow-identity
      MYSQL_USER: deliflow
      MYSQL_PASSWORD: deliflow
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

- name: start identity-server container
  docker:
    name: identity-server
    hostname: identity
    image: "{{ identity_docker_images }}"
    state: reloaded
    pull: always
    memory_limit: 512MB
    insecure_registry: yes
    links:
      - "mysql:mysql-server"
      - "eureka-server:eureka-server"
      - "gocd-server:gocd-server"
    env:
      ACTIVE_PROFILE: "{{ active_profile }}"
      GOCD_SERVER_HOST: gocd-server
      GOCD_USERNAME: "{{ gocd_username }}"
      GOCD_PASSWORD: "{{ gocd_password }}"
      GOCD_SERVER_PORT: "{{ gocd_port }}"
      GOCD_SERVER_ROOT: "{{ gocd_root_path }}"
  when: not production_mode

- debug: var=production_mode
  tags:
    - debug

- name: starts identity-server with production mode
  docker:
    name: identity-server
    hostname: identity
    image: "{{ identity_docker_images }}"
    state: reloaded
    pull: always
    memory_limit: 512MB
    insecure_registry: yes
    links:
      - "mysql:mysql-server"
      - "eureka-server:eureka-server"
    extra_hosts:
      gocd-server: "{{gocd_server}}"
    env:
      ACTIVE_PROFILE: "{{ active_profile }}"
      GOCD_SERVER_HOST: gocd-server
      GOCD_USERNAME: "{{ gocd_username }}"
      GOCD_PASSWORD: "{{ gocd_password }}"
      GOCD_SERVER_PORT: "{{ gocd_port }}"
      GOCD_SERVER_ROOT: "{{ gocd_root_path }}"
  when: production_mode
