---
- docker:
    name: identity-server
    image: registry:5000/leansw/identity-services
    state: started
    pull: always
    insecure_registry: yes
    links:
      - "mysql:mysql-server"
      - "eureka-server:eureka-server"
    tags:
      - docker

- docker:
    name: auth-server
    image: registry:5000/leansw/auth-server
    state: started
    pull: always
    links:
      - "eureka-server:eureka-server"
    insecure_registry: yes
    tags:
      - docker
