---
- docker:
    name: mysql
    image: mysql:5.5
    state: started
    hostname: mysql-server
    memory_limit: 216MB
    env:
      MYSQL_DATABASE: deliflow-identity
      MYSQL_USER: deliflow
      MYSQL_PASSWORD: deliflow
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
