---
- docker:
    name: deliflow-webapp
    image: registry:5000/leansw/deliflow-webapp
    state: present
    pull: always
    insecure_registry: yes
    expose:
      - "9900:80"
    links:
      - "eureka-server:eureka-server"
