---
- docker:
    name: deliflow-webapp
    image: registry:5000/leansw/deliflow-webapp
    state: present
    pull: always
    insecure_registry: yes
    links:
      - - "eureka-server:eureka-server"
