---
- docker:
    name: deliflow-webapp
    image: registry:5000/leansw/deliflow-webapp:release
    state: reloaded
    pull: always
    insecure_registry: yes
    ports:
      - "80:9900"
    links:
      - "eureka-server:eureka-server"
    env:
      ACTIVE_PROFILE: default
