---

- docker:
    name: auth-server
    image: registry:5000/leansw/auth-server
    state: present
    pull: always
    insecure_registry: yes
- docker:
    name: cd-metrics
    image: registry:5000/leansw/cd-metrics
    state: present
    pull: always
    insecure_registry: yes
- docker:
    name: code-metrics
    image: registry:5000/leansw/code-metrics
    state: present
    pull: always
    insecure_registry: yes
- docker:
    name: deliflow-webapp
    image: registry:5000/leansw/deliflow-webapp
    state: present
    pull: always
