---
- docker:
    name: cd-metrics
    image: registry:5000/leansw/cd-metrics
    state: present
    pull: always
    insecure_registry: yes
    expose:
      - "9001:9001"
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
  tags:
    - docker
