---
- docker:
    name: cd-metrics
    hostname: cd-metrics
    image: registry:5000/leansw/cd-metrics:release
    state: reloaded
    pull: always
    insecure_registry: yes
    memory_limit: 1024MB
    ports:
      - "9001:9001"
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
      - "gocd-server:gocd-server"
    env:
      ACTIVE_PROFILE: default
      GOCD_SERVER_HOST: gocd-server
      GOCD_USERNAME: "{{ gocd_username }}"
      GOCD_PASSWORD: "{{ gocd_password }}"
      GOCD_SERVER_PORT: "{{ gocd_port }}"
      GOCD_SERVER_ROOT: "{{ gocd_root_path }}"
  when: not production_mode

- name: starts cd-metrics-server with production mode
  docker:
    name: cd-metrics
    hostname: cd-metrics
    image: registry:5000/leansw/cd-metrics:release
    state: reloaded
    pull: always
    insecure_registry: yes
    memory_limit: 1024MB
    ports:
      - "9001:9001"
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
    extra_hosts:
      gocd-server: "{{gocd_server}}"
    env:
      ACTIVE_PROFILE: default
      GOCD_SERVER_HOST: gocd-server
      GOCD_USERNAME: "{{ gocd_username }}"
      GOCD_PASSWORD: "{{ gocd_password }}"
      GOCD_SERVER_PORT: "{{ gocd_port }}"
      GOCD_SERVER_ROOT: "{{ gocd_root_path }}"
  when: production_mode
