---
- docker:
    name: cd-metrics
    image: registry:5000/leansw/cd-metrics
    state: reloaded
    pull: always
    insecure_registry: yes
    ports:
      - "9001:9001"
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
      - "gocd-server:gocd-server"
    env:
      ACTIVE_PROFILE: default
  tags:
    - docker
    - cd-metrics
