---
- name: start gocd-agent-container
  docker:
    name: gocd-agent
    hostname: go-agent
    image: gocd/gocd-agent
    state: reloaded
    links:
      - "gocd-server:gocd-server"
    env:
      GO_SERVER: gocd-server
