---
- name: start gocd-agent-container
  docker:
    name: gocd-agent
    image: gocd/gocd-agent
    state: started
    memory_limit: 512MB
    links:
      - "gocd-server:gocd-server"
    env:
      GO_SERVER: gocd-server
