---
- name: create config volume mapping gocd config file
  file: path=/data/m2 state=directory mode=0777

- name: start gocd-agent-container
  docker:
    name: gocd-agent
    hostname: go-agent
    image: twleansw/deliflow-standard-agent
    state: reloaded
    volumes:
      - /data/m2:/var/go/.m2:rw
    links:
      - "gocd-server:gocd-server"
    env:
      GO_SERVER: gocd-server
