---
- name: ensure that APT works with the https method, and that CA certificates are installed
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-pip
  tags:
    - docker

- name: Add the new GPG key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  tags:
    - docker

- name: Update local sys source list
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list
  tags:
    - docker

- name: Install docker requirement python package
  pip: name=docker-py version=1.1.0
  tags:
    - docker
