---
- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Set docker daemon options
  copy:
    content: "DOCKER_OPTS=\"{{ docker_opts }}\""
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  when: docker_opts != ""

- lineinfile:
    dest: /lib/systemd/system/docker.service
    insertafter: '^\[Service\]'
    line: "EnvironmentFile=-/etc/default/docker"
    state: present
  register: docker_conf_updated_env1

- lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS"
    state: present
  register: docker_conf_updated_env2

- name: Reload systemd immediately
  command: systemctl daemon-reload
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (docker_conf_updated_env1.changed or docker_conf_updated_env2.changed)
  notify:
    - restart docker engine

- name: Reload systemd immediately
  command: echo restart docker
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (docker_conf_updated_env1.changed or docker_conf_updated_env2.changed)
  notify:
    - restart docker engine
- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.aliyuncs.com
    username: afyao@thoughtworks.com
    email: afyao@thoughtworks.com
    password: Leanswdev1
    reauthorize: yes  
- pip: name=docker-py version=1.7.0
