---
- docker:
    name: code-metrics
    hostname: code-metrics
    image: "registry.aliyuncs.com/leansw/code-metrics:release"
    state: reloaded
    pull: always
    insecure_registry: yes
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
      - "sonarqube:sonar-server"
    env:
      ACTIVE_PROFILE: default
