---
- docker:
    name: code-metrics
    hostname: code-metrics
    image: registry:5000/leansw/code-metrics:release
    state: reloaded
    pull: always
    insecure_registry: yes
    memory_limit: 216MB
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
      - "sonarqube:sonar-server"
    env:
      ACTIVE_PROFILE: default
  tags:
    - docker
    - code-metrics
