---
- docker:
    name: code-metrics
    image: registry:5000/leansw/code-metrics
    state: reloaded
    pull: always
    insecure_registry: yes
    ports:
      - "9003:9003"
    links:
      - "mongodb:mongo-server"
      - "eureka-server:eureka-server"
      - "sonarqube:sonar-server"
  tags:
    - docker
